import { chromium } from 'playwright';
const URL = process.env.SHOT_URL || 'http://localhost:8199/index.html';
const b = await chromium.launch({ args: ['--use-gl=angle', '--use-angle=metal', '--enable-gpu'] });
const p = await b.newPage({ viewport: { width: 390, height: 780 }, deviceScaleFactor: 2 });
p.on('pageerror', e => console.log('[pageerror]', e.message));
p.on('requestfailed', r => console.log('[failed]', r.url()));
p.on('response', r => { if (r.status() >= 400) console.log('[' + r.status() + ']', r.url()); });
await p.goto(URL);
await p.waitForTimeout(6000);
console.log('__game:', await p.evaluate(() => typeof window.__game));
await p.screenshot({ path: (process.env.SHOT_DIR || '/private/tmp/shots') + '/dbg.png' });
await b.close();
