import { chromium } from 'playwright';
const URL = process.env.SHOT_URL || 'http://localhost:8199/index.html';
const b = await chromium.launch({ args: ['--use-gl=angle', '--use-angle=metal', '--enable-gpu'] });
const p = await b.newPage({ viewport: { width: 390, height: 780 }, deviceScaleFactor: 2 });
p.on('pageerror', e => console.log('[pageerror]', e.message, '\n', (e.stack || '').split('\n').slice(0,4).join('\n')));
p.on('console', m => { if (m.type() === 'error') console.log('[console]', m.text()); });
p.on('response', r => { if (r.status() >= 400) console.log('[' + r.status() + ']', r.url()); });
await p.goto(URL);
await p.waitForTimeout(6000);
console.log('__ready:', await p.evaluate(() => window.__ready));
console.log('boot:', await p.evaluate(() => document.getElementById('boot')?.innerText?.slice(0, 200)));
await p.screenshot({ path: (process.env.SHOT_DIR || '/private/tmp/shots') + '/dbg.png' });
await b.close();
